
[types]

	[types.wood_type]

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.quark]
			bamboo = true
			azalea = true
			blossom = true
			ancient = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.extendedmushrooms]
			mushroom = true
			glowshroom = true
			poisonous_mushroom = true
			honey_fungus = true

		[types.wood_type.deeperdarker]
			echo = true

		[types.wood_type.silentgear]
			netherwood = true

	[types.leaves_type]

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.silentgear]
			netherwood = true

		[types.leaves_type.quark]
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true
			ancient = true

[entries]

	[entries.wood_type]

		[entries.wood_type.mcwtrpdoors]
			ranch_trapdoor = true
			beach_trapdoor = true
			swamp_trapdoor = true
			glass_trapdoor = true
			tropical_trapdoor = true
			cottage_trapdoor = true
			paper_trapdoor = true
			bark_trapdoor = true
			classic_trapdoor = true
			bamboo_trapdoor = true
			barn_trapdoor = true
			four_panel_trapdoor = true
			barred_trapdoor = true
			mystic_trapdoor = true

		[entries.wood_type.quark]
			vertical_planks = true
			ladder = true
			post = true
			trapped_chest = true
			chest = true
			hollow_log = true
			bookshelf = true
			stripped_post = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.create]
			window_pane = true
			window = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

